// Generated by scripts/build-generated-modular-scenes.mjs. Do not edit manually.
import type { ModularSceneDefinition } from './modularScenes';

export const GENERATED_MODULAR_SCENES = {} as const satisfies Readonly<Record<string,ModularSceneDefinition>>;
