import type { Recipe } from './types';

type Spec = {
  id: string; name: string; price: number; shake: boolean; category?: Recipe['category'];
  origin: string; story: string; notes: string[]; occasions: string[];
  ingredients: Array<[string, number]>;
};

const makeRecipe = (spec: Spec): Recipe => ({
  id: spec.id,
  name: spec.name,
  price: spec.price,
  needsShake: spec.shake,
  category: spec.category ?? 'cocktail',
  origin: spec.origin,
  story: spec.story,
  tastingNotes: spec.notes,
  occasions: spec.occasions,
  ingredients: spec.ingredients.map(([ingredientId, amount]) => ({ ingredientId, amount })),
  method: spec.shake
    ? ['Add the liquid ingredients to a shaker with ice.', 'Shake firmly until chilled and integrated.', 'Strain into the prepared serving glass.', 'Finish with the recipe garnish and serve immediately.']
    : ['Prepare the serving glass with fresh ice when required.', 'Add the measured ingredients in recipe order.', 'Stir or lift gently until chilled and combined.', 'Finish with the recipe garnish and serve immediately.']
});

export const ADDITIONAL_RECIPES: Recipe[] = [
  makeRecipe({ id:'cuba-libre',name:'Cuba Libre',price:10,shake:false,category:'classic',origin:'Cuba · early 20th century',story:'Rum, cola and fresh lime became an enduring Cuban highball whose citrus edge separates it from a simple mixed drink.',notes:['cola','lime','rum'],occasions:['Casual round','Late night','Easy order'],ingredients:[['white-rum',45],['cola',90],['lime-juice',10],['ice',5],['lime-wedge',1]] }),
  makeRecipe({ id:'dark-stormy',name:"Dark ’n’ Stormy",price:11,shake:false,category:'classic',origin:'Bermuda · early 20th century',story:'Dark rum floats over spicy ginger beer and lime in this dramatic Bermudian highball.',notes:['ginger','dark rum','zesty'],occasions:['Warm evening','Spicy food','Rum fan'],ingredients:[['dark-rum',50],['ginger-beer',90],['lime-juice',15],['ice',5]] }),
  makeRecipe({ id:'tom-collins',name:'Tom Collins',price:10.5,shake:true,category:'classic',origin:'London · 19th century',story:'A tall gin sour lengthened with soda, the Tom Collins is bright, fizzy and built for unhurried refreshment.',notes:['lemon','botanical','sparkling'],occasions:['Brunch','Warm afternoon','Long conversation'],ingredients:[['gin',45],['lemon-juice',25],['sugar-syrup',15],['soda',75],['ice',5]] }),
  makeRecipe({ id:'gin-fizz',name:'Gin Fizz',price:10.5,shake:true,category:'classic',origin:'United States · late 19th century',story:'The fizz family turns a compact gin sour into a lively, foaming highball with a measured splash of soda.',notes:['bright','foamy','botanical'],occasions:['Aperitif','Brunch','Classic drinker'],ingredients:[['gin',45],['lemon-juice',25],['sugar-syrup',15],['soda',45],['ice',4]] }),
  makeRecipe({ id:'gimlet',name:'Gimlet',price:10,shake:true,category:'classic',origin:'Britain · late 19th century',story:'A naval-era combination of gin and preserved lime evolved into one of the cleanest and most direct sours.',notes:['lime','dry','botanical'],occasions:['Aperitif','Quick round','Gin fan'],ingredients:[['gin',60],['lime-juice',25],['sugar-syrup',15],['ice',4]] }),
  makeRecipe({ id:'southside',name:'Southside',price:11,shake:true,category:'classic',origin:'United States · early 20th century',story:'Mint gives the gin sour a cool aromatic lift, creating a polished bridge between a Gimlet and a Mojito.',notes:['mint','lime','fresh'],occasions:['Garden party','Warm evening','Aperitif'],ingredients:[['gin',50],['lime-juice',25],['sugar-syrup',15],['mint',5],['ice',4]] }),
  makeRecipe({ id:'gin-rickey',name:'Gin Rickey',price:9.5,shake:false,category:'classic',origin:'Washington, D.C. · 1880s',story:'The Rickey favors dryness over sweetness, stretching gin and lime with cold soda water.',notes:['dry','lime','sparkling'],occasions:['Low-sugar request','Hot day','Simple order'],ingredients:[['gin',45],['lime-juice',20],['soda',90],['ice',5],['lime-wedge',1]] }),
  makeRecipe({ id:'bees-knees',name:"Bee’s Knees",price:11,shake:true,category:'classic',origin:'Prohibition-era United States',story:'A soft, citrus-led gin sour traditionally sweetened with honey; the bar syrup keeps its rounded balance.',notes:['lemon','soft','floral'],occasions:['Date night','Gin beginner','Aperitif'],ingredients:[['gin',50],['lemon-juice',25],['sugar-syrup',20],['ice',4]] }),
  makeRecipe({ id:'white-lady',name:'White Lady',price:12,shake:true,category:'classic',origin:'London and Paris · 1920s',story:'Gin, orange liqueur and lemon form a crisp, elegant sidecar-style sour.',notes:['citrus','dry','silky'],occasions:['Elegant evening','Aperitif','Classic guest'],ingredients:[['gin',40],['orange-liqueur',25],['lemon-juice',20],['ice',4]] }),
  makeRecipe({ id:'pegu-club',name:'Pegu Club',price:12,shake:true,category:'classic',origin:'Yangon · 1920s',story:'Created for a colonial-era club, this aromatic gin sour layers orange liqueur over sharp lime.',notes:['lime','orange','aromatic'],occasions:['Cocktail enthusiast','Aperitif','Historic choice'],ingredients:[['gin',45],['orange-liqueur',20],['lime-juice',20],['sugar-syrup',5],['ice',4]] }),
  makeRecipe({ id:'corpse-reviver-2',name:'Corpse Reviver Number Two',price:13.5,shake:true,category:'classic',origin:'London · 1930s',story:'A famous equal-parts revival cocktail balancing gin, citrus, orange liqueur and aromatized wine.',notes:['sharp','complex','orange'],occasions:['Brunch','Experienced guest','Historic choice'],ingredients:[['gin',25],['orange-liqueur',25],['vermouth',25],['lemon-juice',25],['ice',4]] }),
  makeRecipe({ id:'vesper',name:'Vesper',price:14,shake:false,category:'classic',origin:'London fiction · 1950s',story:'Gin and vodka share the lead while aromatized wine adds a restrained, fragrant finish.',notes:['strong','dry','botanical'],occasions:['Formal evening','Experienced guest','Slow sip'],ingredients:[['gin',45],['vodka',15],['vermouth',10],['ice',4]] }),
  makeRecipe({ id:'vodka-martini',name:'Vodka Martini',price:12,shake:false,category:'classic',origin:'United States · 20th century',story:'Replacing gin with vodka creates a cleaner, more neutral Martini that foregrounds temperature and texture.',notes:['clean','dry','silky'],occasions:['Formal evening','Vodka fan','Aperitif'],ingredients:[['vodka',60],['vermouth',15],['ice',4]] }),
  makeRecipe({ id:'kamikaze',name:'Kamikaze',price:10.5,shake:true,origin:'United States · 1970s',story:'A compact vodka sour built from equal ideas of clean spirit, orange and lime.',notes:['lime','orange','sharp'],occasions:['Quick round','Party','Vodka fan'],ingredients:[['vodka',35],['orange-liqueur',20],['lime-juice',25],['ice',4]] }),
  makeRecipe({ id:'lemon-drop',name:'Lemon Drop',price:10.5,shake:true,origin:'San Francisco · 1970s',story:'A bright sweet-tart vodka sour inspired by lemon candy and often served with a sugared edge.',notes:['lemon','sweet-tart','clean'],occasions:['Celebration','Vodka beginner','Lively group'],ingredients:[['vodka',45],['lemon-juice',25],['sugar-syrup',20],['ice',4]] }),
  makeRecipe({ id:'cape-codder',name:'Cape Codder',price:9.5,shake:false,origin:'United States · mid-20th century',story:'Vodka and cranberry make a direct ruby highball, sharpened by fresh lime.',notes:['cranberry','tart','easy'],occasions:['Easy order','Casual group','First cocktail'],ingredients:[['vodka',45],['cranberry-juice',90],['lime-juice',10],['ice',5]] }),
  makeRecipe({ id:'sea-breeze',name:'Sea Breeze',price:10,shake:false,origin:'United States · 1980s',story:'Cranberry and grapefruit give this vodka highball a dry, coastal brightness.',notes:['cranberry','grapefruit','crisp'],occasions:['Brunch','Warm day','Casual order'],ingredients:[['vodka',40],['cranberry-juice',60],['grapefruit-soda',60],['ice',5]] }),
  makeRecipe({ id:'bay-breeze',name:'Bay Breeze',price:10,shake:false,origin:'United States · 1980s',story:'A tropical cousin of the Cape Codder, pairing vodka and cranberry with pineapple.',notes:['pineapple','cranberry','soft'],occasions:['Poolside','Easy order','Party'],ingredients:[['vodka',40],['cranberry-juice',60],['pineapple-juice',60],['ice',5]] }),
  makeRecipe({ id:'madras',name:'Madras',price:10,shake:false,origin:'United States · late 20th century',story:'Vodka, cranberry and orange-toned citrus create an easygoing fruit-forward highball.',notes:['berry','citrus','light'],occasions:['Casual group','Brunch','First cocktail'],ingredients:[['vodka',40],['cranberry-juice',75],['orange-liqueur',10],['soda',30],['ice',5]] }),
  makeRecipe({ id:'woo-woo',name:'Woo Woo',price:10.5,shake:true,origin:'United States · 1980s',story:'A playful vodka and cranberry cocktail with an orange-fruit accent and vivid party character.',notes:['cranberry','fruity','bright'],occasions:['Party','Celebration','Lively group'],ingredients:[['vodka',40],['orange-liqueur',20],['cranberry-juice',60],['ice',4]] }),
  makeRecipe({ id:'sex-on-the-beach',name:'Sex on the Beach',price:11.5,shake:true,origin:'Florida · 1980s',story:'A colorful resort-era cocktail blending vodka with cranberry, pineapple and orange liqueur.',notes:['tropical','berry','sweet'],occasions:['Vacation mood','Party','Celebration'],ingredients:[['vodka',35],['orange-liqueur',20],['cranberry-juice',45],['pineapple-juice',45],['ice',5]] }),
  makeRecipe({ id:'french-martini',name:'French Martini',price:12.5,shake:true,origin:'New York · 1980s',story:'A modern fruit Martini combining vodka with pineapple and berry-like cranberry richness.',notes:['pineapple','berry','silky'],occasions:['Date night','Stylish evening','Dessert alternative'],ingredients:[['vodka',45],['pineapple-juice',45],['cranberry-juice',20],['sugar-syrup',5],['ice',4]] }),
  makeRecipe({ id:'black-russian',name:'Black Russian',price:11,shake:false,category:'classic',origin:'Brussels · 1940s',story:'Vodka and coffee liqueur form a compact, dark after-dinner drink with no unnecessary decoration.',notes:['coffee','strong','rich'],occasions:['After dinner','Coffee fan','Slow sip'],ingredients:[['vodka',50],['coffee-liqueur',25],['ice',3]] }),
  makeRecipe({ id:'white-russian',name:'White Russian',price:12,shake:false,origin:'United States · 1960s',story:'A creamy variation on the Black Russian softens vodka and coffee liqueur with a pale, rich layer.',notes:['creamy','coffee','sweet'],occasions:['After dinner','Dessert drink','Relaxed guest'],ingredients:[['vodka',45],['coffee-liqueur',25],['milk',30],['ice',3]] }),
  makeRecipe({ id:'mudslide',name:'Mudslide',price:13,shake:true,origin:'Cayman Islands · 1970s',story:'Coffee liqueur, vodka and milk create a decadent chilled cocktail that behaves like dessert.',notes:['creamy','coffee','decadent'],occasions:['Dessert drink','Celebration','Sweet tooth'],ingredients:[['vodka',30],['coffee-liqueur',30],['milk',40],['ice',5]] }),
  makeRecipe({ id:'boulevardier',name:'Boulevardier',price:14,shake:false,category:'classic',origin:'Paris · 1920s',story:'Whiskey replaces gin in the Negroni structure, producing a warmer and richer bitter aperitivo.',notes:['bitter','warming','rich'],occasions:['Before dinner','Whiskey fan','Slow conversation'],ingredients:[['whiskey',40],['bitter-aperitif',30],['vermouth',30],['ice',3],['orange',1]] }),
  makeRecipe({ id:'manhattan',name:'Manhattan',price:14,shake:false,category:'classic',origin:'New York · late 19th century',story:'A foundational whiskey cocktail where sweet aromatized wine rounds the spirit without hiding it.',notes:['spirit-forward','silky','aromatic'],occasions:['Formal evening','After dinner','Whiskey fan'],ingredients:[['whiskey',60],['vermouth',30],['ice',4],['orange',1]] }),
  makeRecipe({ id:'rob-roy',name:'Rob Roy',price:13.5,shake:false,category:'classic',origin:'New York · 1890s',story:'The Scotch-family answer to the Manhattan keeps the same elegant whiskey-and-vermouth architecture.',notes:['malty','aromatic','strong'],occasions:['Theater night','Whiskey fan','Slow sip'],ingredients:[['whiskey',60],['vermouth',25],['ice',4]] }),
  makeRecipe({ id:'mint-julep',name:'Mint Julep',price:12.5,shake:false,category:'classic',origin:'Southern United States · 19th century',story:'Whiskey, mint, sugar and crushed ice create a fragrant slow-changing drink associated with warm-weather hospitality.',notes:['mint','whiskey','cool'],occasions:['Hot day','Outdoor event','Whiskey beginner'],ingredients:[['whiskey',60],['mint',6],['sugar-syrup',15],['ice',6]] }),
  makeRecipe({ id:'whiskey-highball',name:'Whiskey Highball',price:10.5,shake:false,category:'classic',origin:'Japan and Britain · 20th century',story:'Careful dilution and lively soda turn whiskey into a precise, food-friendly long drink.',notes:['clean','sparkling','whiskey'],occasions:['Dinner','Long session','Simple order'],ingredients:[['whiskey',45],['soda',105],['ice',5]] }),
  makeRecipe({ id:'whiskey-ginger',name:'Whiskey Ginger',price:10.5,shake:false,origin:'International · modern classic',story:'Ginger spice lifts whiskey in an accessible highball with a fresh lime edge.',notes:['ginger','warming','zesty'],occasions:['Casual round','Food pairing','Whiskey beginner'],ingredients:[['whiskey',45],['ginger-beer',90],['lime-juice',10],['ice',5]] }),
  makeRecipe({ id:'lynchburg-lemonade',name:'Lynchburg Lemonade',price:12,shake:true,origin:'Tennessee · 1980s',story:'Whiskey, orange liqueur and lemon are lengthened with soda for a bright Southern highball.',notes:['lemon','whiskey','sparkling'],occasions:['Summer party','Whiskey beginner','Lively group'],ingredients:[['whiskey',40],['orange-liqueur',20],['lemon-juice',25],['sugar-syrup',10],['soda',60],['ice',5]] }),
  makeRecipe({ id:'gold-rush',name:'Gold Rush',price:12.5,shake:true,origin:'New York · early 2000s',story:'A modern whiskey sour strips the format to spirit, lemon and a rounded sweetener.',notes:['lemon','warming','soft'],occasions:['Date night','Whiskey beginner','Cool evening'],ingredients:[['whiskey',50],['lemon-juice',25],['sugar-syrup',20],['ice',4]] }),
  makeRecipe({ id:'sazerac',name:'Sazerac',price:14.5,shake:false,category:'classic',origin:'New Orleans · 19th century',story:'One of America’s oldest named cocktails, pairing whiskey, sugar and aromatic bitterness in a lean ritual serve.',notes:['strong','aromatic','dry'],occasions:['Experienced guest','After dinner','Historic choice'],ingredients:[['whiskey',60],['bitter-aperitif',5],['sugar-syrup',10],['ice',3]] }),
  makeRecipe({ id:'paper-plane',name:'Paper Plane',price:13.5,shake:true,origin:'Chicago · 2000s',story:'A modern equal-parts style sour sets whiskey against bittersweet aperitif and lemon.',notes:['bittersweet','lemon','balanced'],occasions:['Cocktail enthusiast','Aperitif','Modern classic'],ingredients:[['whiskey',30],['bitter-aperitif',30],['vermouth',20],['lemon-juice',25],['ice',4]] }),
  makeRecipe({ id:'rum-runner',name:'Rum Runner',price:13,shake:true,origin:'Florida Keys · 1970s',story:'A tropical rum cocktail combining dark and light spirit with pineapple and bright citrus.',notes:['tropical','rum','fruit'],occasions:['Vacation mood','Party','Tiki night'],ingredients:[['white-rum',30],['dark-rum',30],['pineapple-juice',60],['lime-juice',20],['sugar-syrup',10],['ice',5]] }),
  makeRecipe({ id:'hurricane',name:'Hurricane',price:13.5,shake:true,origin:'New Orleans · 1940s',story:'Created to move plentiful rum, the Hurricane became a bold fruit-forward symbol of New Orleans nightlife.',notes:['rum','tropical','bold'],occasions:['Festival','Party','Experienced guest'],ingredients:[['white-rum',30],['dark-rum',30],['pineapple-juice',60],['lime-juice',20],['cranberry-juice',20],['sugar-syrup',10],['ice',5]] }),
  makeRecipe({ id:'planters-punch',name:"Planter’s Punch",price:12,shake:true,category:'classic',origin:'Jamaica · 19th century',story:'A flexible Caribbean rum punch follows the old balance of strong, weak, sour and sweet.',notes:['dark rum','lime','spice'],occasions:['Warm evening','Group order','Rum fan'],ingredients:[['dark-rum',60],['lime-juice',25],['sugar-syrup',20],['soda',45],['ice',5]] }),
  makeRecipe({ id:'zombie',name:'Zombie',price:16,shake:true,origin:'California · 1930s',story:'A powerful tiki classic layers multiple rums, citrus and tropical fruit into a deceptively smooth drink.',notes:['strong','tropical','complex'],occasions:['Experienced guest','One-drink order','Tiki night'],ingredients:[['white-rum',30],['dark-rum',45],['orange-liqueur',15],['lime-juice',20],['pineapple-juice',60],['sugar-syrup',10],['ice',5]] }),
  makeRecipe({ id:'painkiller',name:'Painkiller',price:13.5,shake:true,origin:'British Virgin Islands · 1970s',story:'Dark rum, pineapple and coconut make a rich island drink designed for slow holiday sipping.',notes:['creamy','pineapple','dark rum'],occasions:['Vacation mood','Dessert drink','Rum fan'],ingredients:[['dark-rum',60],['pineapple-juice',90],['coconut-cream',30],['ice',5]] }),
  makeRecipe({ id:'jungle-bird',name:'Jungle Bird',price:13.5,shake:true,origin:'Kuala Lumpur · 1970s',story:'A rare bitter tiki drink, the Jungle Bird contrasts dark rum and pineapple with Italian-style aperitif.',notes:['bitter','pineapple','rum'],occasions:['Adventurous guest','Tiki night','Aperitif'],ingredients:[['dark-rum',45],['bitter-aperitif',20],['pineapple-juice',45],['lime-juice',15],['sugar-syrup',10],['ice',5]] }),
  makeRecipe({ id:'old-cuban',name:'Old Cuban',price:14.5,shake:true,origin:'New York · early 2000s',story:'Mint, aged-style rum and sparkling wine combine the freshness of a Mojito with the elegance of a French 75.',notes:['mint','sparkling','rum'],occasions:['Celebration','Date night','Welcome drink'],ingredients:[['dark-rum',45],['lime-juice',20],['sugar-syrup',15],['mint',5],['sparkling-wine',60],['ice',4]] }),
  makeRecipe({ id:'el-presidente',name:'El Presidente',price:13.5,shake:false,category:'classic',origin:'Havana · 1910s',story:'A refined Cuban stirred cocktail pairing light rum with vermouth and orange liqueur.',notes:['orange','silky','rum'],occasions:['Formal evening','Aperitif','Historic choice'],ingredients:[['white-rum',45],['vermouth',25],['orange-liqueur',15],['ice',4]] }),
  makeRecipe({ id:'hotel-nacional',name:'Hotel Nacional',price:13,shake:true,category:'classic',origin:'Havana · 1930s',story:'Named for Havana’s grand hotel, this rum sour balances pineapple, lime and orange liqueur.',notes:['pineapple','lime','elegant'],occasions:['Tropical evening','Historic choice','Date night'],ingredients:[['white-rum',45],['pineapple-juice',30],['lime-juice',20],['orange-liqueur',15],['sugar-syrup',5],['ice',4]] }),
  makeRecipe({ id:'aperol-spritz',name:'Aperitivo Spritz',price:11.5,shake:false,category:'classic',origin:'Northern Italy · 20th century',story:'A bittersweet aperitif, sparkling wine and soda form the bright orange ritual of the Italian early evening.',notes:['bittersweet','sparkling','orange'],occasions:['Aperitivo','Brunch','Low-intensity choice'],ingredients:[['bitter-aperitif',45],['sparkling-wine',75],['soda',30],['ice',5],['orange',1]] }),
  makeRecipe({ id:'americano',name:'Americano',price:10.5,shake:false,category:'classic',origin:'Milan · 19th century',story:'Bitter aperitif and vermouth are lengthened with soda for a gentle, aromatic pre-dinner drink.',notes:['bitter','herbal','sparkling'],occasions:['Aperitivo','Long conversation','Lower-strength choice'],ingredients:[['bitter-aperitif',30],['vermouth',30],['soda',75],['ice',5],['orange',1]] }),
  makeRecipe({ id:'negroni-sbagliato',name:'Negroni Sbagliato',price:13,shake:false,origin:'Milan · 1970s',story:'A happy mistake replaces the Negroni’s gin with sparkling wine, making the classic lighter and more celebratory.',notes:['bitter','sparkling','herbal'],occasions:['Aperitivo','Celebration','Brunch'],ingredients:[['bitter-aperitif',30],['vermouth',30],['sparkling-wine',60],['ice',4],['orange',1]] }),
  makeRecipe({ id:'hugo-spritz',name:'Hugo Spritz',price:11.5,shake:false,origin:'South Tyrol · 2000s',story:'Mint, lime, sparkling wine and soda create an alpine spritz with an especially fresh aromatic profile.',notes:['mint','lime','sparkling'],occasions:['Brunch','Garden party','Warm afternoon'],ingredients:[['sparkling-wine',90],['soda',45],['lime-juice',15],['sugar-syrup',10],['mint',5],['ice',5]] })
];
