import type { AlcoholProduct, AlcoholType, BottleOccasion, BottleRequest } from './types';

export const ALCOHOL_TYPE_LABELS: Record<AlcoholType, string> = {
  whiskey: 'Whiskey', bourbon: 'Bourbon', liqueur: 'Liqueur', 'herbal-liqueur': 'Herbal liqueur', 'specialty-liqueur': 'Specialty liqueur', sambuca: 'Sambuca', sangria: 'Sangria', infusion: 'Настойка / Infusion', 'fruit-wine': 'Fruit wine', champagne: 'Champagne',
  'sparkling-wine': 'Sparkling wine', 'port-wine': 'Port wine', cognac: 'Cognac', brandy: 'Brandy', beer: 'Beer', 'non-alcoholic-beer': 'Alcohol-free beer', soju: 'Soju', sake: 'Sake', cider: 'Cider', vodka: 'Vodka', gin: 'Gin', rum: 'Rum', tequila: 'Tequila',
  aperitif: 'Aperitif', vermouth: 'Vermouth'
};

export const ALCOHOL_PRODUCTS: AlcoholProduct[] = [
  { id:'jack-daniels-old-7',name:"Jack Daniel’s Old Number Seven",brand:"Jack Daniel’s",type:'whiskey',volumeMl:700,abv:40,price:42,popularity:98,origin:'Tennessee, USA',tastes:['smooth','vanilla','oak'],occasions:['gift','party','home bar'],description:'A familiar Tennessee whiskey with mellow vanilla, caramel and toasted oak.',ingredientId:'whiskey',color:'#a84b20' },
  { id:'jameson',name:'Jameson Irish Whiskey',brand:'Jameson',type:'whiskey',volumeMl:700,abv:40,price:38,popularity:94,origin:'Ireland',tastes:['smooth','light','vanilla'],occasions:['gift','party','home bar'],description:'Approachable triple-distilled Irish whiskey with a light, smooth finish.',ingredientId:'whiskey',color:'#ba6329' },
  { id:'johnnie-walker-black',name:'Johnnie Walker Black Label',brand:'Johnnie Walker',type:'whiskey',volumeMl:700,abv:40,price:55,popularity:93,origin:'Scotland',tastes:['smoky','rich','oak'],occasions:['gift','dinner','celebration'],description:'A rich blended Scotch with smoke, dried fruit and layered oak.',ingredientId:'whiskey',color:'#80401f' },
  { id:'chivas-regal-12',name:'Chivas Regal 12',brand:'Chivas Regal',type:'whiskey',volumeMl:700,abv:40,price:52,popularity:88,origin:'Scotland',tastes:['smooth','honey','rich'],occasions:['gift','dinner','celebration'],description:'Rounded blended Scotch with honey, orchard fruit and a creamy texture.',ingredientId:'whiskey',color:'#b76725' },
  { id:'jim-beam-white',name:'Jim Beam White Label',brand:'Jim Beam',type:'bourbon',volumeMl:700,abv:40,price:34,popularity:92,origin:'Kentucky, USA',tastes:['vanilla','oak','bold'],occasions:['party','home bar','gift'],description:'Popular Kentucky bourbon with vanilla, corn sweetness and oak spice.',ingredientId:'whiskey',color:'#b85c22' },
  { id:'makers-mark',name:'Maker’s Mark',brand:'Maker’s Mark',type:'bourbon',volumeMl:700,abv:45,price:48,popularity:86,origin:'Kentucky, USA',tastes:['sweet','vanilla','soft'],occasions:['gift','dinner','home bar'],description:'Wheated bourbon known for soft spice, caramel and a rounded finish.',ingredientId:'whiskey',color:'#c66b27' },
  { id:'jagermeister',name:'Jägermeister',brand:'Jägermeister',type:'herbal-liqueur',volumeMl:700,abv:35,price:32,popularity:95,origin:'Germany',tastes:['herbal','bitter','spicy'],occasions:['party','home bar','gift'],description:'A bold German herbal liqueur with citrus peel, spice and bittersweet depth.',ingredientId:'herbal-liqueur',color:'#35522b' },
  { id:'baileys-original',name:'Baileys Original Irish Cream',brand:'Baileys',type:'liqueur',volumeMl:700,abv:17,price:30,popularity:91,origin:'Ireland',tastes:['creamy','sweet','coffee'],occasions:['gift','dinner','celebration'],description:'Creamy Irish liqueur with cocoa, vanilla and coffee-like richness.',ingredientId:'coffee-liqueur',color:'#c8aa82' },
  { id:'cointreau',name:'Cointreau',brand:'Cointreau',type:'liqueur',volumeMl:700,abv:40,price:45,popularity:84,origin:'France',tastes:['orange','dry','bright'],occasions:['gift','home bar','dinner'],description:'A clear orange liqueur balancing bright citrus with a clean dry finish.',ingredientId:'orange-liqueur',color:'#e5a24b' },
  { id:'absolut-blue',name:'Absolut Vodka',brand:'Absolut',type:'vodka',volumeMl:700,abv:40,price:29,popularity:94,origin:'Sweden',tastes:['clean','smooth','neutral'],occasions:['party','home bar','gift'],description:'Clean Swedish vodka with a soft grain character and broad mixing appeal.',ingredientId:'vodka',color:'#dbe7ed' },
  { id:'smirnoff-red',name:'Smirnoff Number Twenty-One',brand:'Smirnoff',type:'vodka',volumeMl:700,abv:40,price:24,popularity:96,origin:'Global',tastes:['clean','light','neutral'],occasions:['party','home bar','celebration'],description:'A widely recognized, budget-friendly vodka with a clean neutral profile.',ingredientId:'vodka',color:'#e7eef1' },
  { id:'grey-goose',name:'Grey Goose',brand:'Grey Goose',type:'vodka',volumeMl:700,abv:40,price:56,popularity:87,origin:'France',tastes:['smooth','soft','clean'],occasions:['gift','celebration','dinner'],description:'Premium French vodka chosen for a smooth texture and polished presentation.',ingredientId:'vodka',color:'#d9e8ed' },
  { id:'bombay-sapphire',name:'Bombay Sapphire',brand:'Bombay Sapphire',type:'gin',volumeMl:700,abv:40,price:34,popularity:92,origin:'England',tastes:['botanical','citrus','dry'],occasions:['gift','home bar','dinner'],description:'A recognizable dry gin with layered botanicals and a bright citrus lift.',ingredientId:'gin',color:'#9ed4db' },
  { id:'beefeater',name:'Beefeater London Dry Gin',brand:'Beefeater',type:'gin',volumeMl:700,abv:40,price:28,popularity:88,origin:'London, England',tastes:['juniper','dry','citrus'],occasions:['party','home bar','gift'],description:'Classic London dry gin with firm juniper and citrus peel.',ingredientId:'gin',color:'#dce8d7' },
  { id:'hendricks',name:'Hendrick’s Gin',brand:'Hendrick’s',type:'gin',volumeMl:700,abv:41,price:48,popularity:86,origin:'Scotland',tastes:['floral','cucumber','soft'],occasions:['gift','dinner','celebration'],description:'Distinctive Scottish gin with floral notes and a cool cucumber accent.',ingredientId:'gin',color:'#ccd9cf' },
  { id:'bacardi-carta-blanca',name:'Bacardí Carta Blanca',brand:'Bacardí',type:'rum',volumeMl:700,abv:40,price:27,popularity:96,origin:'Puerto Rico',tastes:['light','clean','vanilla'],occasions:['party','home bar','celebration'],description:'Light-bodied white rum made for popular highballs and tropical drinks.',ingredientId:'white-rum',color:'#eadfb0' },
  { id:'captain-morgan-dark',name:'Captain Morgan Dark Rum',brand:'Captain Morgan',type:'rum',volumeMl:700,abv:40,price:30,popularity:90,origin:'Caribbean',tastes:['spicy','caramel','rich'],occasions:['party','home bar','gift'],description:'Dark Caribbean-style rum with warm spice, caramel and molasses notes.',ingredientId:'dark-rum',color:'#86401f' },
  { id:'havana-club-3',name:'Havana Club 3 Años',brand:'Havana Club',type:'rum',volumeMl:700,abv:40,price:31,popularity:84,origin:'Cuba',tastes:['light','sugarcane','fresh'],occasions:['party','home bar','dinner'],description:'Fresh Cuban light rum with sugarcane character and gentle oak.',ingredientId:'white-rum',color:'#d7b666' },
  { id:'jose-cuervo-especial',name:'Jose Cuervo Especial Gold',brand:'Jose Cuervo',type:'tequila',volumeMl:700,abv:38,price:30,popularity:92,origin:'Mexico',tastes:['agave','oak','bold'],occasions:['party','celebration','home bar'],description:'Popular gold tequila with roasted agave and gentle oak sweetness.',ingredientId:'tequila',color:'#dfbc61' },
  { id:'patron-silver',name:'Patrón Silver',brand:'Patrón',type:'tequila',volumeMl:700,abv:40,price:65,popularity:89,origin:'Mexico',tastes:['agave','clean','citrus'],occasions:['gift','celebration','dinner'],description:'Premium unaged tequila with clean agave, pepper and citrus.',ingredientId:'tequila',color:'#e7d47d' },
  { id:'aperol',name:'Aperol',brand:'Aperol',type:'aperitif',volumeMl:700,abv:11,price:27,popularity:93,origin:'Italy',tastes:['bittersweet','orange','light'],occasions:['party','dinner','celebration'],description:'Bright Italian aperitif with orange, herbs and gentle bitterness.',ingredientId:'bitter-aperitif',color:'#e4672f' },
  { id:'martini-bianco',name:'Martini Bianco',brand:'Martini',type:'vermouth',volumeMl:750,abv:15,price:22,popularity:85,origin:'Italy',tastes:['herbal','vanilla','light'],occasions:['party','dinner','home bar'],description:'Soft white vermouth with vanilla, herbs and subtle sweetness.',ingredientId:'vermouth',color:'#e5cf91' },
  { id:'moet-imperial',name:'Moët & Chandon Impérial',brand:'Moët & Chandon',type:'champagne',volumeMl:750,abv:12,price:78,popularity:94,origin:'Champagne, France',tastes:['dry','sparkling','elegant'],occasions:['gift','celebration','dinner'],description:'Famous non-vintage Champagne with orchard fruit, fine bubbles and polish.',ingredientId:'sparkling-wine',color:'#ead984' },
  { id:'veuve-clicquot-yellow',name:'Veuve Clicquot Yellow Label',brand:'Veuve Clicquot',type:'champagne',volumeMl:750,abv:12,price:82,popularity:91,origin:'Champagne, France',tastes:['dry','rich','sparkling'],occasions:['gift','celebration','dinner'],description:'Structured Champagne with rich fruit, brioche and persistent bubbles.',ingredientId:'sparkling-wine',color:'#e0c454' },
  { id:'mionetto-prosecco',name:'Mionetto Prosecco',brand:'Mionetto',type:'sparkling-wine',volumeMl:750,abv:11,price:24,popularity:82,origin:'Veneto, Italy',tastes:['light','fruity','sparkling'],occasions:['party','celebration','dinner'],description:'Accessible Italian sparkling wine with fresh fruit and lively bubbles.',ingredientId:'sparkling-wine',color:'#ebdc91' },
  { id:'taylors-lbv-port',name:'Taylor’s Late Bottled Vintage Port',brand:'Taylor’s',type:'port-wine',volumeMl:750,abv:20,price:36,popularity:84,origin:'Douro, Portugal',tastes:['rich','dark fruit','sweet'],occasions:['gift','dinner','home bar'],description:'Full-bodied ruby-style port with dark fruit, spice and a long sweet finish.',ingredientId:'vermouth',color:'#6d1830' },
  { id:'grahams-tawny-10',name:'Graham’s Ten Year Tawny Port',brand:'Graham’s',type:'port-wine',volumeMl:750,abv:20,price:44,popularity:82,origin:'Douro, Portugal',tastes:['nutty','dried fruit','smooth'],occasions:['gift','dinner','celebration'],description:'Mature tawny port with walnuts, dried fruit and mellow barrel character.',ingredientId:'vermouth',color:'#994324' },
  { id:'hennessy-vs',name:'Hennessy VS',brand:'Hennessy',type:'cognac',volumeMl:700,abv:40,price:52,popularity:96,origin:'Cognac, France',tastes:['oak','fruit','bold'],occasions:['gift','party','celebration'],description:'The best-known entry cognac, lively and bold with fruit and toasted oak.',ingredientId:'whiskey',color:'#aa5b24' },
  { id:'remy-martin-vsop',name:'Rémy Martin VSOP',brand:'Rémy Martin',type:'cognac',volumeMl:700,abv:40,price:68,popularity:91,origin:'Cognac, France',tastes:['smooth','vanilla','ripe fruit'],occasions:['gift','dinner','celebration'],description:'Fine Champagne cognac with ripe fruit, vanilla and a rounded texture.',ingredientId:'whiskey',color:'#b66b2a' },
  { id:'courvoisier-vs',name:'Courvoisier VS',brand:'Courvoisier',type:'cognac',volumeMl:700,abv:40,price:49,popularity:86,origin:'Cognac, France',tastes:['floral','fruit','oak'],occasions:['gift','dinner','home bar'],description:'A fragrant cognac with floral lift, fresh fruit and gentle oak spice.',ingredientId:'whiskey',color:'#a75b25' },
  { id:'guinness-draught',name:'Guinness Draught',brand:'Guinness',type:'beer',volumeMl:440,abv:4.2,price:5,popularity:98,origin:'Dublin, Ireland',tastes:['roasted','creamy','bitter'],occasions:['party','dinner','home bar'],description:'Iconic Irish stout with roasted malt, a dry finish and creamy nitrogen texture.',ingredientId:'coffee-liqueur',color:'#24130f' },
  { id:'heineken-original',name:'Heineken Original',brand:'Heineken',type:'beer',volumeMl:330,abv:5,price:4,popularity:97,origin:'Netherlands',tastes:['crisp','light','bitter'],occasions:['party','dinner','home bar'],description:'Globally familiar pale lager with a crisp body and mild hop bitterness.',ingredientId:'sparkling-wine',color:'#d5a62d' },
  { id:'corona-extra',name:'Corona Extra',brand:'Corona',type:'beer',volumeMl:355,abv:4.5,price:4.5,popularity:96,origin:'Mexico',tastes:['light','crisp','citrus'],occasions:['party','celebration','home bar'],description:'Light Mexican lager often served cold with a fresh lime wedge.',ingredientId:'sparkling-wine',color:'#e4b93e' },
  { id:'stella-artois',name:'Stella Artois',brand:'Stella Artois',type:'beer',volumeMl:330,abv:5,price:4.5,popularity:92,origin:'Belgium',tastes:['crisp','malty','dry'],occasions:['party','dinner','home bar'],description:'Belgian pilsner with a clean malt center and a dry, gently bitter finish.',ingredientId:'sparkling-wine',color:'#dca92d' },
  { id:'budweiser',name:'Budweiser',brand:'Budweiser',type:'beer',volumeMl:330,abv:5,price:3.5,popularity:94,origin:'United States',tastes:['light','clean','malty'],occasions:['party','celebration','home bar'],description:'Accessible American lager with a light body and clean malt character.',ingredientId:'sparkling-wine',color:'#d9a12a' },
  { id:'jinro-chamisul-fresh',name:'Jinro Chamisul Fresh',brand:'Jinro',type:'soju',volumeMl:360,abv:16.5,price:8,popularity:97,origin:'South Korea',tastes:['clean','soft','light'],occasions:['party','dinner','home bar'],description:'Korea’s best-known soju: clean, light and designed for shared food occasions.',ingredientId:'vodka',color:'#d8eadf' },
  { id:'chum-churum-original',name:'Chum Churum Original',brand:'Chum Churum',type:'soju',volumeMl:360,abv:16.5,price:8,popularity:88,origin:'South Korea',tastes:['soft','clean','slightly sweet'],occasions:['party','dinner','home bar'],description:'Soft Korean soju with a slightly sweet, easy-drinking profile.',ingredientId:'vodka',color:'#cfe5d5' },
  { id:'gekkeikan-traditional',name:'Gekkeikan Traditional Sake',brand:'Gekkeikan',type:'sake',volumeMl:750,abv:15.6,price:18,popularity:91,origin:'Kyoto, Japan',tastes:['rice','smooth','dry'],occasions:['dinner','gift','home bar'],description:'Versatile Japanese sake with gentle rice aromas and a smooth dry finish.',ingredientId:'sparkling-wine',color:'#e6ddbd' },
  { id:'dassai-45',name:'Dassai Forty-Five Junmai Daiginjo',brand:'Dassai',type:'sake',volumeMl:720,abv:16,price:38,popularity:89,origin:'Yamaguchi, Japan',tastes:['fruity','floral','elegant'],occasions:['gift','dinner','celebration'],description:'Polished premium sake with delicate fruit, floral aroma and an elegant finish.',ingredientId:'sparkling-wine',color:'#e7e0ca' },
  { id:'hakutsuru-junmai',name:'Hakutsuru Junmai',brand:'Hakutsuru',type:'sake',volumeMl:720,abv:15,price:20,popularity:84,origin:'Kobe, Japan',tastes:['rice','savory','smooth'],occasions:['dinner','gift','home bar'],description:'Food-friendly junmai sake with rice depth, mild savoriness and balance.',ingredientId:'sparkling-wine',color:'#e0d8bd' },
  { id:'st-remy-vsop',name:'St-Rémy VSOP Brandy',brand:'St-Rémy',type:'brandy',volumeMl:700,abv:40,price:28,popularity:83,origin:'France',tastes:['vanilla','fruit','smooth'],occasions:['gift','dinner','home bar'],description:'French brandy with vanilla, ripe fruit and a mellow oak finish.',ingredientId:'whiskey',color:'#a75520' },
  { id:'torres-10',name:'Torres Ten Gran Reserva',brand:'Torres',type:'brandy',volumeMl:700,abv:38,price:30,popularity:85,origin:'Spain',tastes:['rich','vanilla','cinnamon'],occasions:['gift','dinner','home bar'],description:'Spanish grape brandy with vanilla, cinnamon and a rich mature character.',ingredientId:'whiskey',color:'#99491f' },
  { id:'strongbow-original',name:'Strongbow Original Cider',brand:'Strongbow',type:'cider',volumeMl:500,abv:5,price:5,popularity:92,origin:'England',tastes:['apple','dry','crisp'],occasions:['party','dinner','home bar'],description:'Popular English cider with crisp apple, firm acidity and a dry finish.',ingredientId:'sparkling-wine',color:'#d6a337' },
  { id:'somersby-apple',name:'Somersby Apple Cider',brand:'Somersby',type:'cider',volumeMl:330,abv:4.5,price:4.5,popularity:90,origin:'Denmark',tastes:['apple','sweet','fruity'],occasions:['party','celebration','home bar'],description:'Sweet, fruit-forward apple cider with lively carbonation and broad appeal.',ingredientId:'sparkling-wine',color:'#d8b83f' },
  { id:'magners-original',name:'Magners Original Irish Cider',brand:'Magners',type:'cider',volumeMl:568,abv:4.5,price:6,popularity:86,origin:'Ireland',tastes:['apple','smooth','crisp'],occasions:['party','dinner','home bar'],description:'Irish cider with ripe apple flavor, gentle sweetness and a crisp finish.',ingredientId:'sparkling-wine',color:'#c9952d' },
  { id:'molinari-extra',name:'Molinari Sambuca Extra',brand:'Molinari',type:'sambuca',volumeMl:700,abv:42,price:31,popularity:93,origin:'Italy',tastes:['anise','sweet','herbal'],occasions:['party','dinner','home bar'],description:'Classic Italian sambuca with an intense star-anise aroma and a rich sweet finish.',ingredientId:'bitter-aperitif',color:'#e7ece8' },
  { id:'luxardo-sambuca',name:'Luxardo Sambuca dei Cesari',brand:'Luxardo',type:'sambuca',volumeMl:700,abv:38,price:34,popularity:87,origin:'Italy',tastes:['anise','spicy','sweet'],occasions:['gift','dinner','home bar'],description:'Traditional clear sambuca with concentrated anise, herbs and warm spice.',ingredientId:'bitter-aperitif',color:'#e1e8e5' },
  { id:'ramazzotti-sambuca',name:'Ramazzotti Sambuca',brand:'Ramazzotti',type:'sambuca',volumeMl:700,abv:38,price:28,popularity:84,origin:'Italy',tastes:['anise','sweet','smooth'],occasions:['party','dinner','home bar'],description:'Smooth Italian anise liqueur commonly served neat, chilled or with coffee beans.',ingredientId:'bitter-aperitif',color:'#e4e9e2' },
  { id:'don-simon-sangria',name:'Don Simón Sangria',brand:'Don Simón',type:'sangria',volumeMl:1500,abv:7,price:10,popularity:92,origin:'Spain',tastes:['fruity','citrus','sweet'],occasions:['party','dinner','celebration'],description:'Accessible Spanish red-wine sangria with citrus and ripe fruit, ready to serve chilled.',ingredientId:'vermouth',color:'#8f2432' },
  { id:'lolea-number-one',name:'Lolea Number One Red Sangria',brand:'Lolea',type:'sangria',volumeMl:750,abv:7,price:18,popularity:88,origin:'Spain',tastes:['fruity','citrus','spicy'],occasions:['gift','party','celebration'],description:'Premium bottled red sangria with Mediterranean citrus, fruit and gentle spice.',ingredientId:'vermouth',color:'#a22b39' },
  { id:'penasol-sangria',name:'Peñasol Sangria',brand:'Peñasol',type:'sangria',volumeMl:1000,abv:7,price:9,popularity:82,origin:'Spain',tastes:['berry','orange','sweet'],occasions:['party','dinner','home bar'],description:'Easy-drinking Spanish sangria with red berries, orange and light sweetness.',ingredientId:'vermouth',color:'#98273b' },
  { id:'nemiroff-honey-pepper',name:'Nemiroff Honey Pepper',brand:'Nemiroff',type:'infusion',volumeMl:700,abv:40,price:24,popularity:91,origin:'Ukraine',tastes:['honey','spicy','herbal'],occasions:['gift','dinner','home bar'],description:'Ukrainian honey-and-pepper infused spirit balancing sweetness with warming chili spice.',ingredientId:'vodka',color:'#ca7b28' },
  { id:'zubrowka-bison-grass',name:'Żubrówka Bison Grass',brand:'Żubrówka',type:'infusion',volumeMl:700,abv:37.5,price:25,popularity:90,origin:'Poland',tastes:['herbal','vanilla','grass'],occasions:['gift','dinner','home bar'],description:'Polish bison-grass flavored spirit with herbal, vanilla and fresh meadow aromas.',ingredientId:'vodka',color:'#c5b54d' },
  { id:'beluga-hunting-herbal',name:'Beluga Hunting Herbal',brand:'Beluga Hunting',type:'infusion',volumeMl:700,abv:40,price:38,popularity:80,origin:'Eastern Europe',tastes:['herbal','spicy','bitter'],occasions:['gift','dinner','home bar'],description:'A strong herbal infusion built around aromatic plants, spice and bittersweet depth.',ingredientId:'bitter-aperitif',color:'#7e6d32' },
  { id:'riga-black-balsam',name:'Riga Black Balsam',brand:'Riga Black Balsam',type:'infusion',volumeMl:700,abv:45,price:30,popularity:86,origin:'Latvia',tastes:['herbal','bitter','dark fruit'],occasions:['gift','dinner','home bar'],description:'Dark Baltic herbal infusion with roots, berries, spice and a powerful bittersweet finish.',ingredientId:'bitter-aperitif',color:'#35231d' },
  { id:'boones-strawberry-hill',name:"Boone’s Farm Strawberry Hill",brand:"Boone’s Farm",type:'fruit-wine',volumeMl:750,abv:7.5,price:7,popularity:78,origin:'California, USA',tastes:['strawberry','sweet','fruity'],occasions:['party','home bar','celebration'],description:'Light strawberry-flavored fruit wine with an easy, sweet party profile.',ingredientId:'fruit-wine',color:'#d94a68' },
  { id:'mauiwine-maui-blanc',name:'MauiWine Maui Blanc Pineapple Wine',brand:'MauiWine',type:'fruit-wine',volumeMl:750,abv:11,price:22,popularity:82,origin:'Hawaii, USA',tastes:['pineapple','tropical','bright'],occasions:['gift','dinner','celebration'],description:'Dry-to-medium Hawaiian pineapple wine with bright tropical fruit and fresh acidity.',ingredientId:'fruit-wine',color:'#e6bc45' },
  { id:'choya-original',name:'CHOYA Original Umeshu',brand:'CHOYA',type:'fruit-wine',volumeMl:750,abv:10,price:21,popularity:90,origin:'Japan',tastes:['plum','sweet','fruity'],occasions:['gift','dinner','home bar'],description:'Popular Japanese plum drink with fragrant stone fruit and balanced sweetness.',ingredientId:'fruit-wine',color:'#d4a244' },
  { id:'heineken-zero',name:'Heineken 0.0',brand:'Heineken 0.0',type:'non-alcoholic-beer',volumeMl:330,abv:0,price:3.5,popularity:96,origin:'Netherlands',tastes:['crisp','malty','light'],occasions:['party','dinner','home bar'],description:'Alcohol-free pale lager with familiar malt, fruit and a gently bitter finish.',ingredientId:'alcohol-free-beer',color:'#d7ad31' },
  { id:'guinness-zero',name:'Guinness 0.0',brand:'Guinness 0.0',type:'non-alcoholic-beer',volumeMl:440,abv:0,price:5,popularity:91,origin:'Dublin, Ireland',tastes:['roasted','creamy','dark'],occasions:['party','dinner','home bar'],description:'Alcohol-free stout preserving Guinness-like roast, dark malt and creamy texture.',ingredientId:'alcohol-free-beer',color:'#231713' },
  { id:'corona-cero',name:'Corona Cero',brand:'Corona Cero',type:'non-alcoholic-beer',volumeMl:330,abv:0,price:4,popularity:90,origin:'Mexico',tastes:['light','crisp','citrus'],occasions:['party','celebration','home bar'],description:'Light alcohol-free Mexican lager suited to cold service with a lime wedge.',ingredientId:'alcohol-free-beer',color:'#e0bb44' },
  { id:'budweiser-zero',name:'Budweiser Zero',brand:'Budweiser Zero',type:'non-alcoholic-beer',volumeMl:330,abv:0,price:3,popularity:88,origin:'United States',tastes:['light','clean','malty'],occasions:['party','dinner','home bar'],description:'Clean alcohol-free American lager for guests who want beer without alcohol.',ingredientId:'alcohol-free-beer',color:'#d19a2e' },
  { id:'becherovka-original',name:'Becherovka Original',brand:'Becherovka',type:'herbal-liqueur',volumeMl:700,abv:38,price:26,popularity:87,origin:'Czech Republic',tastes:['herbal','spicy','cinnamon'],occasions:['gift','dinner','home bar'],description:'Czech herbal liqueur with warming cinnamon, clove and bittersweet botanicals.',ingredientId:'herbal-liqueur',color:'#c3a234' },
  { id:'fernet-branca',name:'Fernet-Branca',brand:'Fernet-Branca',type:'herbal-liqueur',volumeMl:700,abv:39,price:35,popularity:89,origin:'Italy',tastes:['bitter','herbal','minty'],occasions:['gift','dinner','home bar'],description:'Powerfully bitter Italian amaro with mint, roots, spice and a dry finish.',ingredientId:'herbal-liqueur',color:'#33231b' },
  { id:'green-chartreuse',name:'Green Chartreuse',brand:'Chartreuse',type:'herbal-liqueur',volumeMl:700,abv:55,price:70,popularity:88,origin:'France',tastes:['herbal','spicy','complex'],occasions:['gift','dinner','celebration'],description:'Intense French monastic liqueur made from a secret botanical recipe.',ingredientId:'herbal-liqueur',color:'#86a93d' },
  { id:'bols-blue-curacao',name:'Bols Blue Curaçao',brand:'Bols',type:'specialty-liqueur',volumeMl:700,abv:21,price:20,popularity:92,origin:'Netherlands',tastes:['orange','sweet','citrus'],occasions:['party','home bar','celebration'],description:'Bright blue orange liqueur used for vivid tropical and party cocktails.',ingredientId:'blue-curacao',color:'#159bd2' },
  { id:'de-kuyper-blue-curacao',name:'De Kuyper Blue Curaçao',brand:'De Kuyper',type:'specialty-liqueur',volumeMl:700,abv:20,price:18,popularity:89,origin:'Netherlands',tastes:['orange','sweet','bright'],occasions:['party','home bar','celebration'],description:'Popular blue citrus liqueur bringing orange flavor and strong visual color.',ingredientId:'blue-curacao',color:'#168fd0' },
  { id:'midori-melon',name:'Midori Melon Liqueur',brand:'Midori',type:'specialty-liqueur',volumeMl:700,abv:20,price:28,popularity:91,origin:'Japan',tastes:['melon','sweet','fruity'],occasions:['party','home bar','celebration'],description:'Neon-green Japanese melon liqueur created for sweet, colorful cocktails.',ingredientId:'specialty-liqueur',color:'#78bd2c' },
  { id:'malibu-coconut',name:'Malibu Coconut Liqueur',brand:'Malibu',type:'specialty-liqueur',volumeMl:700,abv:21,price:24,popularity:94,origin:'Caribbean',tastes:['coconut','sweet','tropical'],occasions:['party','home bar','celebration'],description:'Sweet coconut-flavored Caribbean rum liqueur with broad tropical appeal.',ingredientId:'specialty-liqueur',color:'#ece1bb' },
  { id:'disaronno-originale',name:'Disaronno Originale',brand:'Disaronno',type:'specialty-liqueur',volumeMl:700,abv:28,price:31,popularity:90,origin:'Italy',tastes:['almond','sweet','marzipan'],occasions:['gift','dinner','home bar'],description:'Famous Italian amaretto-style liqueur with almond and marzipan character.',ingredientId:'specialty-liqueur',color:'#9d4b24' }
];

export const bottleTotal = (product: AlcoholProduct, quantity: number, marketFactor = 1) =>
  Number((product.price * quantity * marketFactor).toFixed(2));

// Popular premium labels use the rare-currency reserve market. Customer crystal payments always
// exceed the refill price, preserving a positive seller margin.
// A new bar starts with only a few mainstream basics for the classic cocktails (one rum, gin, vodka, tequila, whiskey,
// vermouth and a few beers). Every other label, premium ones included, is topped up with crystals first.
export const STARTER_BOTTLE_IDS: readonly string[] = ['bacardi-carta-blanca', 'beefeater', 'smirnoff-red', 'jose-cuervo-especial', 'jim-beam-white', 'martini-bianco', 'heineken-original', 'corona-extra', 'budweiser'];
export const isStarterBottle = (product: AlcoholProduct) => STARTER_BOTTLE_IDS.includes(product.id);
export const isPremiumBottle = (product: AlcoholProduct) => !isStarterBottle(product) && ((product.popularity >= 90 && product.price >= 20) || product.price >= 40);
export const bottleRestockCrystalCost = (product: AlcoholProduct) => Math.min(24, Math.max(isPremiumBottle(product) ? 5 : 2, Math.round(product.price / 4)));
export const bottleSaleCrystalReward = (product: AlcoholProduct, quantity = 1) => {
  const cost = bottleRestockCrystalCost(product);
  return (cost ? cost + Math.max(2, Math.ceil(cost * .3)) : 3) * Math.max(1, quantity);
};
export const brandedServeCrystalReward = (product: AlcoholProduct) => Math.max(3, Math.min(15, Math.ceil(product.popularity / 12)));

export function generateBottleRequest(product: AlcoholProduct, quantity: number, occasion: BottleOccasion, marketFactor = 1): BottleRequest {
  const total = product.price * quantity * marketFactor;
  return {
    productId: product.id,
    quantity,
    budget: Math.ceil(total * (1.05 + Math.random() * .12)),
    type: product.type,
    tastes: product.tastes.slice(0, 2),
    occasion,
    preferredBrand: Math.random() < .3 ? product.brand : undefined
  };
}
