import { createApp, h } from 'vue';
import { createPinia } from 'pinia';
import { createInitialState } from '../src/sim/state';
import TopHud from '../src/components/game/TopHud.vue';
import BarScene from '../src/components/game/BarScene.vue';
import UiIcon from '../src/components/ui/UiIcon.vue';
const now = Date.now();
const sample = createInitialState(now);
const first = sample.customers[0]!;
const last = structuredClone(first);
Object.assign(first,{seatId:0,name:'Mia',patience:3600,patienceRemaining:3600});
Object.assign(last,{seatId:4,id:first.id+'-preview',name:'Zahra',patience:3600,patienceRemaining:3600});
sample.customers=[first,last];
sample.activeCustomerId=first.id;
sample.startingBarChosen=true;
sample.seatNextCustomerAt=[0,now+600000,now+1200000,now+1800000,0];
const storage=new Map<string,string>([['barlingo-offline-v2',JSON.stringify(sample)]]);
Object.defineProperty(window,'localStorage',{value:{getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key),clear:()=>storage.clear(),key:(index:number)=>[...storage.keys()][index]??null,get length(){return storage.size;}}});
for(const path of ['style','dashboard','game','conversation','management','learning','knowledge','ui-kit','polish']) await import(`../src/${path}.css`);
const nav=[['Bar','cocktail'],['Study','book'],['Storage','box'],['Circle','heart'],['Friends','users']];
createApp({render:()=>h('div',{class:'velvet-app service-mode'},[h(TopHud),h('main',{},h('section',{class:'service-layout'},h(BarScene))),h('nav',{class:'game-nav','aria-label':'Preview navigation'},nav.map(([label,icon],index)=>h('button',{class:{active:index===0}},[h(UiIcon,{name:icon}),h('b',label)])))])}).use(createPinia()).mount('#app');
