from pathlib import Path
import re

path = Path('C:/Users/kubai/.codex/visualizations/2026/10/07/01a11537-35c9-7660-8318-346e7cc5f58f/bar-customizer-design.html')
translations = {
    'Дизайн настройки всего бара': 'Bar customization design',
    'Отдельный редактор': 'Dedicated editor',
    'Редактор всех частей бара': 'Bar customization editor',
    'ОФОРМЛЕНИЕ': 'CUSTOMIZATION',
    'Настроить бар': 'Customize bar',
    'Части бара': 'Bar parts',
    'Предпросмотр бара с выбранными частями и пейзажем': 'Preview of the selected bar parts and scenery',
    'Предпросмотр': 'Preview',
    'Вид за окнами': 'Outside view',
    'Варианты выбранной части бара': 'Options for the selected bar part',
    'Масштаб выбранной части': 'Selected part scale',
    'Масштаб': 'Scale',
    'Без несохранённых изменений': 'No unsaved changes',
    'Отменить': 'Undo',
    'Применить оформление': 'Apply design',
    'Помещение': 'Room',
    'Полки': 'Shelves',
    'Стойка': 'Counter',
    'Сиденья': 'Seating',
    'Бутылки': 'Bottles',
    'Свет': 'Lighting',
    'За окнами': 'Outside',
    'Исходный вид': 'Original view',
    'Город': 'City skyline',
    'Крыши города': 'City rooftops',
    'Неоновый город': 'Neon city',
    'Зимние горы': 'Winter mountains',
    'Тропический пляж': 'Tropical beach',
    'Ночная марина': 'Marina at night',
    'Пустыня': 'Desert',
    'Тропический лес': 'Tropical forest',
    'Полночный город': 'Midnight skyline',
    'Дворцовый сад': 'Palace garden',
    'Ночной Париж': 'Paris at night',
    'Закат над риадом': 'Riad sunset',
    'Кадр бара': 'Bar view',
    'Изменения пока не применены': 'Changes not applied',
    'Исходный вид комнаты. Для изменения масштаба выберите другой пейзаж.': 'Original room view. Select another scenery to adjust its scale.',
    'Масштабируется только пейзаж за окнами. Рамы и перила остаются на месте.': 'Only the scenery scales. Window frames and railings stay in place.',
    'Банка стоит на столешнице и масштабируется вместе со стойкой и барменом.': 'The tip jar stays on the countertop and scales with the counter and bartender.',
    'Гости масштабируются вместе со своими сиденьями.': 'Guests scale with their seats.',
    'Бутылки масштабируются вместе с полками.': 'Bottles scale with the shelves.',
    'Выбрать: ': 'Select: ',
    'Количество сидений': 'Seat count',
    'Velvet · исходные': 'Velvet · original',
    'Классический бар': 'Classic cocktails',
    'Премиальный виски': 'Premium whiskey',
    'Винный погреб': 'Wine cellar',
    'Повседневные': 'Everyday spirits',
    'Фэнтези-эликсиры': 'Fantasy elixirs',
    'Неоновые напитки': 'Neon drinks',
    'Тёплый': 'Warm',
    'Розовый': 'Rose',
    'Синий': 'Blue',
    'Фиолетовый': 'Violet',
    'Изумрудный': 'Emerald',
    'Холодный': 'Cool',
    'Яркость света': 'Light intensity',
    '12 пейзажей + исходный': '12 scenes + original',
    ' варианта': ' options',
    ' вариантов': ' options',
    'Оформление применено в предпросмотре': 'Design applied to preview',
}
text = path.read_text(encoding='utf-8')
for original, translated in sorted(translations.items(), key=lambda item: -len(item[0])):
    text = text.replace(original, translated)
text = text.replace('<div id="bar-customizer-design"', '<div lang="en" id="bar-customizer-design"')
assert not re.search('[А-Яа-яЁё]', text), 'Untranslated Russian text remains'
path.write_text(text, encoding='utf-8')
print('All editor labels, accessibility text and status messages are in English.')
