import type { VocabEntry } from './vocabulary';

// Words for the situations that can happen at a bar: first aid, emergencies and security, payments in different
// currencies, broken things, rules and laws, feelings and small talk, and celebrations. The emergency numbers used in
// this game: 101 fire, 102 police, 103 ambulance, 104 gas emergency, 112 the general emergency number.

const w = (
  word: string, ipa: string, pos: VocabEntry['pos'], topic: VocabEntry['topic'], level: VocabEntry['level'],
  meaning: string, example: string, extra: Partial<Pick<VocabEntry, 'opposite' | 'related' | 'note' | 'forms'>> = {}
): VocabEntry => ({ word, ipa, pos, topic, level, meaning, example, ...extra });

export const SITUATION_VOCABULARY: VocabEntry[] = [
  // ---- First aid ----
  w('headache', '/ˈhedeɪk/', 'noun', 'First aid', 'A2', 'A pain in your head.', 'I have a terrible headache.', { forms: ['headaches'] }),
  w('painkiller', '/ˈpeɪnˌkɪlə/', 'noun', 'First aid', 'B1', 'A medicine that stops pain.', 'Do you have a painkiller?', { related: ['pill', 'tablet'] }),
  w('pill', '/pɪl/', 'noun', 'First aid', 'A2', 'A small, hard piece of medicine that you swallow.', 'Take one pill with water.', { related: ['tablet'], forms: ['pills'] }),
  w('tablet', '/ˈtæblət/', 'noun', 'First aid', 'B1', 'Another word for a pill.', 'I take a tablet every morning.', { forms: ['tablets'] }),
  w('medicine', '/ˈmedsn/', 'noun', 'First aid', 'A2', 'Something you take to feel better when you are ill.', 'Are you allergic to any medicine?'),
  w('doctor', '/ˈdɒktə/', 'noun', 'First aid', 'A1', 'A person who helps sick people.', 'Please see a doctor if it hurts tomorrow.', { forms: ['doctors'] }),
  w('ambulance', '/ˈæmbjələns/', 'noun', 'First aid', 'A2', 'A special car that takes sick or hurt people to hospital.', 'I am calling an ambulance.', { note: 'In this game the ambulance number is 103.', forms: ['ambulances'] }),
  w('paramedic', '/ˌpærəˈmedɪk/', 'noun', 'First aid', 'B1', 'A trained person who helps in an emergency and travels in an ambulance.', 'The paramedics arrived in five minutes.', { forms: ['paramedics'] }),
  w('emergency', '/ɪˈmɜːdʒənsi/', 'noun', 'First aid', 'A2', 'A sudden, dangerous situation that needs fast action.', 'This is an emergency. Please call 103.', { forms: ['emergencies'] }),
  w('pain', '/peɪn/', 'noun', 'First aid', 'A2', 'The bad feeling when a part of your body hurts.', 'I have a strong pain in my chest.'),
  w('hurt', '/hɜːt/', 'verb', 'First aid', 'A2', 'To feel pain, or to cause pain.', 'Where does it hurt?', { forms: ['hurts', 'hurting'] }),
  w('dizzy', '/ˈdɪzi/', 'adjective', 'First aid', 'B1', 'Feeling that everything is spinning.', 'I feel dizzy. Can I sit down?'),
  w('faint', '/feɪnt/', 'verb', 'First aid', 'B1', 'To suddenly lose consciousness for a short time.', 'She fainted because she did not eat all day.', { forms: ['faints', 'fainted', 'fainting'] }),
  w('unconscious', '/ʌnˈkɒnʃəs/', 'adjective', 'First aid', 'B1', 'Not awake and not able to hear or feel.', 'He is unconscious. Call an ambulance!', { opposite: 'conscious' }),
  w('breathe', '/briːð/', 'verb', 'First aid', 'A2', 'To take air into your body and let it out.', 'Breathe in slowly, and out.', { forms: ['breathes', 'breathing', 'breathed'] }),
  w('chest', '/tʃest/', 'noun', 'First aid', 'A2', 'The front part of your body between your neck and your stomach.', 'I have a pain in my chest.'),
  w('heart', '/hɑːt/', 'noun', 'First aid', 'A1', 'The part of the body that pushes blood around.', 'My heart is beating very fast.'),
  w('bleed', '/bliːd/', 'verb', 'First aid', 'B1', 'To lose blood.', 'The cut is bleeding a lot.', { forms: ['bleeds', 'bleeding', 'bled'] }),
  w('blood', '/blʌd/', 'noun', 'First aid', 'A2', 'The red liquid in your body.', 'There is blood on the floor.'),
  w('bandage', '/ˈbændɪdʒ/', 'noun', 'First aid', 'B1', 'A long piece of cloth that you wrap around a wound.', 'I will wrap a bandage around your hand.', { forms: ['bandages'] }),
  w('plaster', '/ˈplɑːstə/', 'noun', 'First aid', 'B1', 'A small sticky cover for a small cut.', 'Do you have a plaster for my finger?', { note: 'American English: Band-Aid.', forms: ['plasters'] }),
  w('antiseptic', '/ˌæntiˈseptɪk/', 'noun', 'First aid', 'B1', 'A liquid or cream that cleans a wound and kills germs.', 'Put some antiseptic on the cut.'),
  w('tourniquet', '/ˈtʊənɪkeɪ/', 'noun', 'First aid', 'B1', 'A tight band that stops very heavy bleeding on an arm or a leg.', 'A tourniquet is only for very serious bleeding.', { note: 'Use it only if pressing on the wound does not stop the bleeding. Call 103.' }),
  w('first aid kit', '/ˌfɜːst ˈeɪd kɪt/', 'noun', 'First aid', 'A2', 'A box with bandages, plasters and other things for small accidents.', 'The first aid kit is under the bar.'),
  w('wound', '/wuːnd/', 'noun', 'First aid', 'B1', 'A cut or an injury on the body.', 'Wash the wound with clean water.', { forms: ['wounds'] }),
  w('cut', '/kʌt/', 'noun', 'First aid', 'A2', 'A small opening in the skin made by something sharp.', 'He has a cut on his hand.', { forms: ['cuts'] }),
  w('burn', '/bɜːn/', 'noun', 'First aid', 'B1', 'An injury from fire, heat or hot liquid.', 'Put the burn under cool running water.', { forms: ['burns'] }),
  w('blister', '/ˈblɪstə/', 'noun', 'First aid', 'B1', 'A small bubble of liquid on the skin after a burn.', 'Do not pop the blister.', { forms: ['blisters'] }),
  w('swelling', '/ˈswelɪŋ/', 'noun', 'First aid', 'B1', 'A part of the body that becomes bigger because of an injury or an allergy.', 'There is a swelling around her eye.', { forms: ['swell', 'swollen'] }),
  w('rash', '/ræʃ/', 'noun', 'First aid', 'B1', 'Red spots on the skin.', 'I have a rash on my arm.'),
  w('choke', '/tʃəʊk/', 'verb', 'First aid', 'B1', 'To be unable to breathe because something is stuck in your throat.', 'He is choking on a peanut!', { forms: ['chokes', 'choked', 'choking'] }),
  w('cough', '/kɒf/', 'verb', 'First aid', 'A2', 'To push air out of your throat with a noise.', 'Try to cough hard.', { forms: ['coughs', 'coughed', 'coughing'] }),
  w('recovery position', '/rɪˈkʌvəri pəˌzɪʃn/', 'noun', 'First aid', 'B1', 'A safe way to lay an unconscious person on their side so they can breathe.', 'Put him in the recovery position.'),
  w('panic', '/ˈpænɪk/', 'noun', 'First aid', 'B1', 'A sudden, very strong fear.', 'She had a panic attack.', { forms: ['panicked', 'panicking'] }),
  w('anxious', '/ˈæŋkʃəs/', 'adjective', 'First aid', 'B1', 'Very worried and nervous.', 'I feel anxious before a big meeting.'),
  w('vomit', '/ˈvɒmɪt/', 'verb', 'First aid', 'B1', 'To bring food and drink up from your stomach through your mouth.', 'I think I am going to vomit.', { forms: ['vomits', 'vomited', 'vomiting'], note: 'Informal: be sick, throw up.' }),
  w('sick', '/sɪk/', 'adjective', 'First aid', 'A2', 'Ill, or feeling that you will vomit.', 'I feel sick. I need some fresh air.'),
  w('fresh air', '/ˌfreʃ ˈeə/', 'noun', 'First aid', 'A2', 'Clean, cool air from outside.', 'Let us go outside for some fresh air.'),
  w('allergy pen', '/ˈælədʒi pen/', 'noun', 'First aid', 'B1', 'A pen with medicine that people use for a very strong allergic reaction.', 'Do you have an allergy pen with you?', { note: 'Also called an epinephrine pen.' }),

  // ---- Emergencies & security ----
  w('police', '/pəˈliːs/', 'noun', 'Emergencies & security', 'A2', 'The people who keep the law and protect people.', 'I am calling the police.', { note: 'In this game the police number is 102.' }),
  w('fire brigade', '/ˈfaɪə brɪˌɡeɪd/', 'noun', 'Emergencies & security', 'B1', 'The people who put out fires.', 'Call the fire brigade on 101.'),
  w('firefighter', '/ˈfaɪəˌfaɪtə/', 'noun', 'Emergencies & security', 'B1', 'A person who puts out fires.', 'The firefighters arrived quickly.', { forms: ['firefighters'] }),
  w('gas', '/ɡæs/', 'noun', 'Emergencies & security', 'A2', 'A substance that burns, used for cooking and heating.', 'I smell gas in the kitchen.', { note: 'The gas emergency number is 104.' }),
  w('gas leak', '/ˈɡæs liːk/', 'noun', 'Emergencies & security', 'B1', 'A hole or a crack where gas comes out.', 'There is a gas leak in the kitchen.', { forms: ['gas leaks'] }),
  w('smoke', '/sməʊk/', 'noun', 'Emergencies & security', 'A2', 'The grey cloud that comes from a fire.', 'There is smoke in the kitchen!'),
  w('alarm', '/əˈlɑːm/', 'noun', 'Emergencies & security', 'B1', 'A loud sound that warns people of danger.', 'Press the alarm button.', { forms: ['alarms'] }),
  w('fire extinguisher', '/ˈfaɪər ɪkˌstɪŋɡwɪʃə/', 'noun', 'Emergencies & security', 'B1', 'A red container that puts out a small fire.', 'Pull the pin and aim the fire extinguisher at the base of the fire.'),
  w('exit', '/ˈeksɪt/', 'noun', 'Emergencies & security', 'A2', 'The way out of a building.', 'Please leave through the nearest exit.', { forms: ['exits'] }),
  w('evacuate', '/ɪˈvækjueɪt/', 'verb', 'Emergencies & security', 'B1', 'To leave a dangerous place quickly and safely.', 'Everybody must evacuate the building.', { forms: ['evacuates', 'evacuated', 'evacuating'] }),
  w('threat', '/θret/', 'noun', 'Emergencies & security', 'B1', 'Words that say someone will hurt you.', 'That is a threat. I will call the police.', { forms: ['threats', 'threaten', 'threatened'] }),
  w('robbery', '/ˈrɒbəri/', 'noun', 'Emergencies & security', 'B1', 'A crime where someone takes money by force or by fear.', 'There was a robbery at the shop.', { forms: ['robberies', 'robber'] }),
  w('thief', '/θiːf/', 'noun', 'Emergencies & security', 'B1', 'A person who steals.', 'A thief stole my wallet.', { forms: ['thieves', 'steal', 'stole', 'stolen'] }),
  w('wallet', '/ˈwɒlɪt/', 'noun', 'Emergencies & security', 'A2', 'A small flat case for money and cards.', 'My wallet is gone!', { forms: ['wallets'] }),
  w('suspicious', '/səˈspɪʃəs/', 'adjective', 'Emergencies & security', 'B1', 'Looking strange or dangerous, so that you do not trust it.', 'That man looks suspicious.'),
  w('security guard', '/sɪˈkjʊərəti ɡɑːd/', 'noun', 'Emergencies & security', 'B1', 'A person whose job is to keep a place safe.', 'The security guard walked him out.'),
  w('danger', '/ˈdeɪndʒə/', 'noun', 'Emergencies & security', 'A2', 'The possibility that something bad will happen.', 'Please stay away. There is danger.', { forms: ['dangerous'] }),
  w('follow', '/ˈfɒləʊ/', 'verb', 'Emergencies & security', 'A2', 'To walk or drive behind someone.', 'A man is following me.', { forms: ['follows', 'followed', 'following'] }),
  w('report', '/rɪˈpɔːt/', 'verb', 'Emergencies & security', 'B1', 'To tell the police or an officer about a crime or a problem.', 'I will report this to the police.', { forms: ['reports', 'reported', 'reporting'] }),
  w('calm down', '/ˌkɑːm ˈdaʊn/', 'phrase', 'Emergencies & security', 'A2', 'To become less angry or less afraid.', 'Please calm down. I want to help you.', { note: 'Tip: with a panic attack, “I am here” works better than “calm down”.' }),

  // ---- Payments & currency ----
  w('QR code', '/ˌkjuː ˈɑː kəʊd/', 'noun', 'Payments & currency', 'A2', 'A square code that you scan with your phone to pay.', 'Please scan the QR code to pay.'),
  w('scan', '/skæn/', 'verb', 'Payments & currency', 'A2', 'To read a code with a phone or a machine.', 'Scan the code with your banking app.', { forms: ['scans', 'scanned', 'scanning'] }),
  w('banking app', '/ˈbæŋkɪŋ æp/', 'noun', 'Payments & currency', 'B1', 'A phone program for your bank account.', 'Which banking app do you use?'),
  w('transfer', '/ˈtrænsfɜː/', 'noun', 'Payments & currency', 'B1', 'Sending money from one bank account to another.', 'Can I pay by bank transfer?', { forms: ['transfers'] }),
  w('IBAN', '/ˈaɪbæn/', 'noun', 'Payments & currency', 'B1', 'The long international number of a bank account in Europe.', 'Our IBAN is on the receipt.'),
  w('account', '/əˈkaʊnt/', 'noun', 'Payments & currency', 'B1', 'A place at a bank where your money is kept.', 'I have money in my account.', { forms: ['accounts'] }),
  w('exchange rate', '/ɪksˈtʃeɪndʒ reɪt/', 'noun', 'Payments & currency', 'B1', 'The price of one money in another money.', 'The exchange rate today is one to one.'),
  w('currency', '/ˈkʌrənsi/', 'noun', 'Payments & currency', 'B1', 'The kind of money a country uses.', 'What currency do you have?', { forms: ['currencies'] }),
  w('dollar', '/ˈdɒlə/', 'noun', 'Payments & currency', 'A1', 'The money of the United States and some other countries.', 'I only have dollars.', { forms: ['dollars'] }),
  w('euro', '/ˈjʊərəʊ/', 'noun', 'Payments & currency', 'A1', 'The money used in many European countries.', 'We take euros here.', { forms: ['euros'] }),
  w('local money', '/ˌləʊkl ˈmʌni/', 'phrase', 'Payments & currency', 'A2', 'The money of the country you are in.', 'Sorry, we only take local money.'),
  w('banknote', '/ˈbæŋknəʊt/', 'noun', 'Payments & currency', 'B1', 'A piece of paper money.', 'This banknote looks strange.', { forms: ['banknotes'] }),
  w('fake', '/feɪk/', 'adjective', 'Payments & currency', 'B1', 'Not real; made to look real.', 'I think this note is fake.', { opposite: 'real', related: ['counterfeit'] }),
  w('counterfeit', '/ˈkaʊntəfɪt/', 'adjective', 'Payments & currency', 'B1', 'Made to look like real money, but false.', 'Counterfeit money is a crime.'),
  w('declined', '/dɪˈklaɪnd/', 'adjective', 'Payments & currency', 'B1', 'Not accepted by the bank. Said about a card payment.', 'The machine says my card was declined.'),
  w('terminal', '/ˈtɜːmɪnl/', 'noun', 'Payments & currency', 'B1', 'The small machine where you pay by card.', 'Please put your card in the terminal.', { forms: ['terminals'] }),
  w('contactless', '/ˈkɒntæktləs/', 'adjective', 'Payments & currency', 'B1', 'Paying by touching your card or phone on the terminal.', 'Is the card contactless?'),
  w('PIN', '/pɪn/', 'noun', 'Payments & currency', 'A2', 'The secret number of your bank card.', 'Please enter your PIN.'),
  w('UzCard', '/ˈʌzkɑːd/', 'noun', 'Payments & currency', 'B1', 'A local bank card system in Uzbekistan.', 'Do you take UzCard?'),
  w('Humo', '/ˈhuːməʊ/', 'noun', 'Payments & currency', 'B1', 'Another local bank card system in Uzbekistan.', 'I have a Humo card.'),
  w('owe', '/əʊ/', 'verb', 'Payments & currency', 'B1', 'To have to pay money to someone.', 'I owe you ten dollars.', { forms: ['owes', 'owed', 'owing'] }),
  w('on the house', '/ɒn ðə ˈhaʊs/', 'phrase', 'Payments & currency', 'B1', 'Free; paid by the bar.', 'This drink is on the house.'),
  w('pay back', '/ˌpeɪ ˈbæk/', 'phrase', 'Payments & currency', 'B1', 'To give money back to someone you owe.', 'I will pay you back tomorrow.'),

  // ---- Breakage & damage ----
  w('glass', '/ɡlɑːs/', 'noun', 'Breakage & damage', 'A1', 'A drinking cup made of glass; also the clear, hard material.', 'He dropped his glass.', { forms: ['glasses'] }),
  w('break', '/breɪk/', 'verb', 'Breakage & damage', 'A2', 'To make something fall into pieces.', 'Be careful. You can break the glass.', { forms: ['breaks', 'broke', 'broken', 'breaking'] }),
  w('pieces', '/ˈpiːsɪz/', 'noun', 'Breakage & damage', 'A2', 'Small parts of something broken.', 'The glass broke into pieces.'),
  w('sweep', '/swiːp/', 'verb', 'Breakage & damage', 'B1', 'To clean a floor with a brush.', 'I will sweep up the glass.', { forms: ['sweeps', 'swept', 'sweeping'] }),
  w('spill', '/spɪl/', 'verb', 'Breakage & damage', 'B1', 'To let a liquid fall out by accident.', 'Oh no, I spilled my drink!', { forms: ['spills', 'spilled', 'spilling'] }),
  w('stool', '/stuːl/', 'noun', 'Breakage & damage', 'B1', 'A seat with no back, usually at a bar.', 'The stool broke.', { forms: ['stools'] }),
  w('damage', '/ˈdæmɪdʒ/', 'noun', 'Breakage & damage', 'B1', 'Harm done to a thing.', 'Who will pay for the damage?', { forms: ['damaged'] }),
  w('repair', '/rɪˈpeə/', 'verb', 'Breakage & damage', 'B1', 'To fix something that is broken.', 'We must repair the stool.', { forms: ['repairs', 'repaired', 'repairing'] }),
  w('accident', '/ˈæksɪdənt/', 'noun', 'Breakage & damage', 'A2', 'Something bad that happens by chance, not on purpose.', 'It was an accident.', { forms: ['accidents'] }),
  w('clean up', '/ˌkliːn ˈʌp/', 'phrase', 'Breakage & damage', 'A2', 'To make a place clean and tidy again.', 'I will clean it up.'),
  w('insurance', '/ɪnˈʃʊərəns/', 'noun', 'Breakage & damage', 'B1', 'An agreement where a company pays when something is lost or broken.', 'Our insurance pays for this.'),

  // ---- Rules & law ----
  w('law', '/lɔː/', 'noun', 'Rules & law', 'A2', 'A rule made by the government that everybody must follow.', 'It is the law.', { forms: ['laws'] }),
  w('rule', '/ruːl/', 'noun', 'Rules & law', 'A2', 'A statement about what you can and can not do.', 'It is the rule for everyone.', { forms: ['rules'] }),
  w('allowed', '/əˈlaʊd/', 'adjective', 'Rules & law', 'A2', 'Permitted; you can do it.', 'Pets are not allowed in the bar.', { opposite: 'forbidden', forms: ['allow', 'allows'] }),
  w('forbidden', '/fəˈbɪdn/', 'adjective', 'Rules & law', 'B1', 'Not permitted; against the rules.', 'Smoking is forbidden inside.', { opposite: 'allowed' }),
  w('fine', '/faɪn/', 'noun', 'Rules & law', 'B1', 'Money you must pay as a punishment.', 'The bar got a fine.', { forms: ['fines'] }),
  w('warning', '/ˈwɔːnɪŋ/', 'noun', 'Rules & law', 'B1', 'A message that tells you to be careful or you will be punished.', 'This is a warning, not a fine.', { forms: ['warnings'] }),
  w('inspector', '/ɪnˈspektə/', 'noun', 'Rules & law', 'B1', 'An official who checks that rules are followed.', 'The inspector checked our licence.', { forms: ['inspectors'] }),
  w('boarding pass', '/ˈbɔːdɪŋ pɑːs/', 'noun', 'Rules & law', 'A2', 'The paper or phone code that lets you get on a plane.', 'May I see your boarding pass?'),
  w('duty-free', '/ˌdjuːti ˈfriː/', 'adjective', 'Rules & law', 'B1', 'Sold in an airport without the usual taxes.', 'Duty-free bottles are for travellers only.'),
  w('flight', '/flaɪt/', 'noun', 'Rules & law', 'A2', 'A journey in a plane.', 'My flight leaves at nine.', { forms: ['flights'] }),
  w('traveller', '/ˈtrævələ/', 'noun', 'Rules & law', 'A2', 'A person who is on a trip.', 'Only travellers can buy duty-free bottles.', { forms: ['travellers'] }),
  w('terrace', '/ˈterəs/', 'noun', 'Rules & law', 'B1', 'An outdoor place with tables next to a bar.', 'You can smoke on the terrace.', { forms: ['terraces'] }),
  w('pet', '/pet/', 'noun', 'Rules & law', 'A1', 'An animal that lives with a person, like a dog or a cat.', 'Pets are not allowed.', { forms: ['pets'] }),
  w('service dog', '/ˈsɜːvɪs dɒɡ/', 'noun', 'Rules & law', 'B1', 'A dog trained to help a person who needs it. It is welcome everywhere.', 'He is a service dog. Please let us in.'),
  w('exception', '/ɪkˈsepʃn/', 'noun', 'Rules & law', 'B1', 'A case where a rule does not apply.', 'I can not make an exception.', { forms: ['exceptions'] }),

  // ---- Guests & feelings ----
  w('angry', '/ˈæŋɡri/', 'adjective', 'Guests & feelings', 'A1', 'Feeling very annoyed or cross.', 'The guest is angry about the bill.', { opposite: 'calm' }),
  w('upset', '/ʌpˈset/', 'adjective', 'Guests & feelings', 'A2', 'Unhappy and worried because something bad happened.', 'She looks upset.'),
  w('lonely', '/ˈləʊnli/', 'adjective', 'Guests & feelings', 'A2', 'Sad because you are alone.', 'He feels lonely tonight.'),
  w('nervous', '/ˈnɜːvəs/', 'adjective', 'Guests & feelings', 'A2', 'A little afraid or worried.', 'I am nervous about my first date.'),
  w('excited', '/ɪkˈsaɪtɪd/', 'adjective', 'Guests & feelings', 'A1', 'Very happy and full of energy.', 'We are excited about the match.'),
  w('tipsy', '/ˈtɪpsi/', 'adjective', 'Guests & feelings', 'B1', 'A little drunk, but still happy and in control.', 'She is a bit tipsy.'),
  w('sober', '/ˈsəʊbə/', 'adjective', 'Guests & feelings', 'B1', 'Not drunk.', 'I am completely sober.', { opposite: 'drunk' }),
  w('hiccup', '/ˈhɪkʌp/', 'noun', 'Guests & feelings', 'B1', 'A small, sudden sound in your throat that you can not stop.', 'He has the hiccups.', { forms: ['hiccups'] }),
  w('small talk', '/ˈsmɔːl tɔːk/', 'noun', 'Guests & feelings', 'B1', 'Light, friendly talk about everyday things.', 'Good bartenders are great at small talk.'),
  w('compliment', '/ˈkɒmplɪmənt/', 'noun', 'Guests & feelings', 'B1', 'Something nice that you say about a person.', 'Thank you for the compliment.', { forms: ['compliments'] }),
  w('flirt', '/flɜːt/', 'verb', 'Guests & feelings', 'B1', 'To behave in a romantic way towards someone for fun.', 'He was flirting with the bartender.', { forms: ['flirts', 'flirted', 'flirting'] }),
  w('uncomfortable', '/ʌnˈkʌmftəbl/', 'adjective', 'Guests & feelings', 'B1', 'Feeling uneasy or a little afraid.', 'That makes me uncomfortable.', { opposite: 'comfortable' }),
  w('respect', '/rɪˈspekt/', 'verb', 'Guests & feelings', 'B1', 'To treat someone politely and listen to what they want.', 'Please respect my answer.', { forms: ['respects', 'respected', 'respecting'] }),
  w('polite', '/pəˈlaɪt/', 'adjective', 'Guests & feelings', 'A2', 'Having good manners.', 'Be polite, even when a guest is rude.', { opposite: 'rude' }),
  w('rude', '/ruːd/', 'adjective', 'Guests & feelings', 'A2', 'Not polite.', 'That was a very rude thing to say.', { opposite: 'polite' }),
  w('argue', '/ˈɑːɡjuː/', 'verb', 'Guests & feelings', 'B1', 'To speak angrily with someone because you do not agree.', 'Please do not argue with the other guests.', { forms: ['argues', 'argued', 'arguing', 'argument'] }),

  // ---- Celebrations ----
  w('birthday', '/ˈbɜːθdeɪ/', 'noun', 'Celebrations', 'A1', 'The day when you were born, celebrated every year.', 'It is my friend’s birthday today.', { forms: ['birthdays'] }),
  w('candle', '/ˈkændl/', 'noun', 'Celebrations', 'A2', 'A stick of wax that you light to make light.', 'Could you bring a candle for the cake?', { forms: ['candles'] }),
  w('cake', '/keɪk/', 'noun', 'Celebrations', 'A1', 'A sweet food made from flour, eggs and sugar.', 'We would like a small cake.'),
  w('propose', '/prəˈpəʊz/', 'verb', 'Celebrations', 'B1', 'To ask someone to marry you.', 'He is going to propose tonight.', { forms: ['proposes', 'proposed', 'proposing', 'proposal'] }),
  w('ring', '/rɪŋ/', 'noun', 'Celebrations', 'A2', 'A piece of jewellery that you wear on a finger.', 'He has a ring in his pocket.', { forms: ['rings'] }),
  w('champagne', '/ʃæmˈpeɪn/', 'noun', 'Celebrations', 'A2', 'A sparkling white wine from France, for celebrations.', 'We would like a bottle of champagne.'),
  w('congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'noun', 'Celebrations', 'A2', 'Words you say when somebody is happy about good news.', 'Congratulations on your new job!'),
  w('lottery', '/ˈlɒtəri/', 'noun', 'Celebrations', 'B1', 'A game where you win money if your numbers are chosen.', 'He won the lottery!'),
  w('musician', '/mjuˈzɪʃn/', 'noun', 'Celebrations', 'A2', 'A person who plays music.', 'A musician would like to play here.', { forms: ['musicians'] }),
  w('guitar', '/ɡɪˈtɑː/', 'noun', 'Celebrations', 'A2', 'A musical instrument with strings.', 'She plays the guitar.'),
  w('photo', '/ˈfəʊtəʊ/', 'noun', 'Celebrations', 'A1', 'A picture taken with a camera.', 'May I take a photo of my drink?', { forms: ['photos'] }),
  w('famous', '/ˈfeɪməs/', 'adjective', 'Celebrations', 'A2', 'Known by many people.', 'A famous actor is at table five.'),
  w('review', '/rɪˈvjuː/', 'noun', 'Celebrations', 'B1', 'A text that says what someone thinks of a place or a product.', 'The magazine wrote a good review.', { forms: ['reviews'] }),
  w('power cut', '/ˈpaʊə kʌt/', 'noun', 'Celebrations', 'B1', 'A time when the electricity stops.', 'There is a power cut. Please stay seated.')
];
